### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by DevMSri** [sachinsenal0x64/dotfiles#15]
I want to install your qtile dotfile for its minimal and monochrome layout but I'm not quite sure how to specifically install the qtile stuff without installing all the other configs for things like nvim and others on this repo. Please help, thank you.

**Comment by sachinsenal0x64** [comment]
Hey, sorry for the late reply. First, **you need to install Qtile** using the command 
`pacman -S qtile python-pywal polybar` Then, copy the `Qtile` and `Polybar` folders to `~/.config/ `in your home directory. That's it Also, create a `dotfiles` directory in your home `(~/)` directory. Then copy and paste the `scripts` and `wallpaper` folders into it.

If you have any problems while installing, feel free to ask questions.

**Comment by DevMSri** [comment]
I'm not sure if I followed your instructions incorrectly but after running what you suggested and then following the Qtile reload, my system just showed the wallpaper with nothing else and my mouse wasn't working on the screen. Could you send a video of how to do it, in a VM or something so I can better implement what you suggested earlier? Sorry for the inconvenience.
